import Head from "next/head";
import styles from "../styles/Home.module.css";
import Sidebar from "../components/Sidebar";
import {Flex, Text, IconButton} from "@chakra-ui/react";
import {FiMenu} from "react-icons/fi";

export default function Home() {
  return (
    <div className={styles.container}>
      <Flex w='100%'>
        <Sidebar />
      </Flex>
      <Head>
        <title>Treck The Hill</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Treck The Hill</h1>
      </main>
    </div>
  );
}
